### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by SaraiQX** [THUNLP-MT/PS-VAE#2]
Dear THUNLP team,
Thanks for your amazing work. 
I'm trying to practice your code and found the below error. Could you pls enlighten me a bit about the solution? Thank you!

(xxx-env) root@autodl-container....:~/autodl-tmp/PS-VAE-main/src/data# python ./mol_bpe.py 
Traceback (most recent call last):
  File "./mol_bpe.py", line 13, in <module>
    from utils.chem_utils import molecule2smiles, smiles2molecule, get_submol 
ModuleNotFoundError: No module named 'utils'

**Comment by kxz18** [comment]
Hi, this is because the utils.py is located in *src* instead of *src/data*. If you want to run the script under *src/data*, you need to extend the module search path by `export PYTHONPATH=$PYTHONPATH:~/autodl-tmp/PS-VAE-main/src` . A better way may be directly running it under *src* by `python -m data.mol_bpe`.

**Comment by kxz18** [comment]
Hi~ Is the problem solved? If so, may you close the issue?

**Comment by SaraiQX** [comment]
Dear author, 
Many thanks for your kind help. Sorry for my delay due to the latest pandemic. First of all, the ps part worked well, that's very exciting. 

So I again tried to implement the main program ( the code is well organized btw). And found that the issue "ModuleNotFoundError: No module named 'utils'" occurred despite my efforts to use "export PYTHONPATH" method etc.

However, when mol_bpe.py was moved to the outer folder just like generate.py, the following command worked well.

`python PS-VAE/data/mol_bpe.py --data PS-VAE/dataset/zinc250k/train.txt --output PS-VAE/zinc_bpe_300.txt --vocab_size 300`

Due to my limited programming knowledge, I cannot explain it well. Just let you know about my experience. I'll keep practicing the whole program. Happy New Year to you all.
Best,
Sarai

**Comment by kxz18** [comment]
As far as I know, python searches for modules from the directory of the script, the pathes in PYTHONPATH and the installed dependencies. In this case, the module **utils** is located under **PS-VAE/src**, but **mol_bpe.py** is located under **PS-VAE/src/data**, so wherever you run the script directly by `python /path/to/mol_bpe.py`, python will search for the module **utils** under **PS-VAE/src/data**, leading to the ModuleNotFound error. If you move **mol_bpe.py** to the same folder as **generate.py**, python will search **utils** under **PS-VAE/src ** because the script is located there. That's the reason why the ModuleNotFound error does not occur anymore. It should have worked if you export the absolute path of **PS-VAE/src** to PYTHONPATH, so is it possible that the path you export to PYTHONPATH is not correct? Moreover, by running `python -m data.mol_bpe` under **PS-VAE/src**, python will automatically add the current work directory (i.e. **PS-VAE/src**) to the search path, which may also solve the problem.
