### ISSUE TITLE
Difference in ps and src folder

### ISSUE THREAD

**Issue by windyLemon** [THUNLP-MT/PS-VAE#4]
Hi author,
https://github.com/THUNLP-MT/PS-VAE/blob/57e289a087d96d54356247d1d7a5757767c673cd/src/data/mol_bpe.py#L73
this function in ps folder is difference and i have test this will lead different split of the molecule. Does this will influence the final result or which is right?

**Comment by windyLemon** [comment]
I test CCOc1ccc(OCC)c(C2C(C#N)=C(N)N(c3ccccc3C(F)(F)F)C3=C2C(=O)CCC3)c1 with unkekulize setting

**Comment by kxz18** [comment]
Hi, the implementation details of the extraction algorithm are slightly different in ps and src, because ps is polished and provided for those who are only interested in the subgraph-level representation (e.g. support for unkekulized setting and fix of some corner cases). If you want to strictly reproduce the results in the paper, then the src folder should be used. Otherwise I think both are ok.

**Comment by windyLemon** [comment]
OK, thanks!
